title: <p align="center"> Dhandapani Subramanian </p>
logo: /assets/img/logo.png
description:
  <p align="center">
  <a href="https://www.linkedin.com/in/dhandapani-subramanian-522a0b4/">LinkedIn</a> |
  <a href="https://github.com/sdpani">GitHub</a>
  
  <br>   
  PLM Principal Consultant, Solution Architect.
  Now striving to encorporate Data Science and Machine Learning in Product Lifecycle Management domain.
  
  <br>
  </p>


theme: jekyll-theme-minimal
